#Mejorar escogiendo la version
FROM ultralytics/ultralytics:latest-jetson-jetpack6

# Include new modules in the task manager file
COPY ultralytics/OrinNanoSup/nn/tasks.py /ultralytics/ultralytics/nn

# General V8DetectionLoss (Loss function + Weighted BCE) function:
COPY ultralytics/OrinNanoSup/utils/loss.py /ultralytics/ultralytics/utils

# Additional Loss metrics (WIoU and MPDIoU)
COPY ultralytics/OrinNanoSup/utils/metrics.py /ultralytics/ultralytics/utils

# New modules: block, attention, conv, pooling
COPY modules /ultralytics/modules

# Trained models
COPY models /ultralytics/models

# Change dataset directory in settings.json
COPY ultralytics/.config/settings.json /root/.config/Ultralytics

# Install vim editor
#RUN apt-get update
#RUN apt-get install -y vim 

#python
#from ultralytics import YOLO
#model = YOLO("models/exported/v5n_Base/weights/best.engine")
#model.export(format="engine")			# -> 32 bits FP representation
#model.export(format="engine", half=True)	# -> 16 bits FP representation
#model.val(data="/ultralytics/datasets/DsLMF_minerBehaviorDataset.yaml")
